add better github action test

diff --git a/.github/workflows/docker_build.yml b/.github/workflows/docker_build.yml
--- a/.github/workflows/docker_build.yml
+++ b/.github/workflows/docker_build.yml
@@ -30,4 +30,11 @@ jobs:
 
       - name: Run Docker Container and generate mp3
         run: |
-          docker run -v $(pwd)/examples/lorem_ipsum.txt:/app/examples/lorem_ipsum.txt quickpiperaudiobook /app/examples/lorem_ipsum.txt --mp3
+          docker run -v $(pwd)/examples:/app/examples quickpiperaudiobook /app/examples/lorem_ipsum.txt --mp3 --output /app
+
+      - name: Verify MP3 File Exists
+        run: |
+          if [ ! -f "/app/lorem_ipsum.mp3" ]; then
+            echo "Error: lorem_ipsum.mp3 was not generated!"
+            exit 1
+          fi
